### ISSUE TITLE
read fragments get counted multiple times

### ISSUE THREAD

**Issue by orionzhou** [secastel/allelecounter#1]
This is not the correct way of counting allele-specific read fragments since reads overlapping/spanning multiple het-SNPs will be counted multiple times. But in fact each read pair/fragment should be counted only once.

**Comment by secastel** [comment]
Allelecounter produces counts at the level of SNPs, so any reads that overlap a SNP will be counted. If you are doing an analysis that aggregates data across SNPs you are correct that you will be double counting reads. If you are interested in analyzing ASE not at the SNP level, but at, for example, a gene, I suggest you use our other tool, phASER (https://github.com/secastel/phaser), which properly aggregates data across SNPs.
